#!/bin/bash

usage() {
    echo "shell-script [-t] [-m some-msg]"
    echo "-t | --test             -- some option"
    echo "-m some-msg             -- an option with argument"
    echo "--help                  -- even more help"
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

MSG="some value"

main() {
   echo $MSG
   exit 0   
}

validateArg() {
    if [ $1 -eq 0 ]; then
	echo "$2"
	exit 1
    fi
}

while [ $# -ne 0 ]; do
    NUM_ARGS_BEFORE=$#	
    if [ x${1} == x"-t" ]; then
    	#do something when option "-t" is passed
	echo "you have passed option -t"
        shift
    fi	
    if [ x${1} == x"-m" ]; then
        shift
	validateArg $# "-m requires a message to be passed"
	MSG=$1
        shift
    fi   
    if [ x${1} == x"--help" ]; then
        echo "you can display some help message"
	exit 0
    fi 
    NUM_ARGS_AFTER=$#
    if [ $NUM_ARGS_BEFORE -eq $NUM_ARGS_AFTER ]; then
        echo "Invalid argument: $1"
	exit 1
    fi
done

main
